### ISSUE TITLE
Need to update dependency of "ws@^0.7.1"

### ISSUE THREAD

**Issue by aborovsky** [PaulAvery/kodi-ws#11]
ws@^0.7.1 too old and depends on old bufferutil@1.0.x which cannot be compiled for node.js >=4.x.x 
I've tested with latest ws and it's compiled successfully.
But did't try: is it works nice.
Guys, can you try in your own environment?

My env:

`bash-3.2$ node -v

v4.4.3

bash-3.2$ npm -v

2.15.1`

**Comment by bartels** [comment]
I tested with ws@1.1.0 and my app works fine with the update version.  The example apps run without problems too (with the exception of an unrelated bug I found: #12 )

tested with node v4.4.4
