### ISSUE TITLE
incompatibility with Node V0.10.x

### ISSUE THREAD

**Issue by Fjuxx** [PaulAvery/kodi-ws#5]
Hi,

i noticed that the library is not compatible with Node versions that do not have Promise integrated.

i created a fork which uses Bluebird for the primises instead of the NodeJS integrated one.
This makes it compatible with the older versions of NodeJS as well.

In theory this should be faster as well, but i don't know it well enough to know for sure ;)

Perhaps it is an idea to use Bluebird instead of NodeJS, but i do not know what the implications may be for other users.

**Comment by PaulAvery** [comment]
Hi. Yes I just rely on ES6 Promises being available in the runtime.

I would happily accept PRs using [native-or-bluebird](https://www.npmjs.com/package/native-or-bluebird) for this as well as for [jrpc-schema](https://github.com/PaulAvery/node-jrpc-schema).

**Comment by PaulAvery** [comment]
Closing this, because I personally am not very invested in this. Especially now that node v4 is out already.
