### ISSUE TITLE
Batch requests

### ISSUE THREAD

**Issue by Bram77** [PaulAvery/kodi-ws#7]
Thank you for this very elegant library! It's working great and I love the minimalistic approach.

For my application I need to do batch requests to Kodi. I can't figure out how to do this with the jrpc-schema library. Do you know if this is possible?

**Comment by PaulAvery** [comment]
Hi, I don't think I have anything implemented for batch requests right now. And yes, the documentation for jrpc-schema seems all over the place. Let me have a look at that.

**Comment by Bram77** [comment]
Thank you Florian. I do understand how the library works. But your code is very compact and efficient. I'm not seeing an 'in' to add batch support without having to rewrite almost the whole thing. I hoped maybe you'd see a way to avoid that. I'm a quite experienced PHP developer (about 20 years), and I'm absolutely not Javascript-shy, but my Javascript knowledge and experience don't seem to be sufficient enough to be able to add this functionality without destroying the elegance and efficiency of your code.

**Comment by PaulAvery** [comment]
Ok, hmm.

In that case what exactly do you use the batch mode for / how would you need it to work?
Do you need batch mode because you need the results at the same time or do you need it, because the number of requests you can send is limited? I am not sure what you are trying to achieve. And without that knowledge I don't know how to help you :)

**Comment by PaulAvery** [comment]
Oh and btw, I just pulled in your changes (dependency updates and renaming). And two things, first you should at least specify that my original code was BSD-3-Clause licensed and you have to provide the license with my name in it in your fork. I should include the GPLv2 in my repo as well I guess? As I see it you intended to relicense your contributions to it?

**Comment by Bram77** [comment]
I'm sorry! I really don't know anything about licenses. I've reverted back to your license and published the changes. As you've now merged my changes, my for has become a bit obsolete :). Maybe it's better if I pull it from bower, since it'll only confuse.

I'm not trying to hijack your project in any way. Often developers do not respond to issue. So I forked yours.

**Comment by Bram77** [comment]
I'll provide you with example situations in which batch requests are really useful (if not required) this evening.

[Here](http://www.jsonrpc.org/specification#batch) you can find the official specifications for batch requests. Kodi supports this. 

Tolriq (the developer of the well known Yatse android remote) told me you really can't do without the batch requests, if you want a reliable application. And I'm starting to see that's true.

**Comment by PaulAvery** [comment]
Don't be sorry :)
I am happy someone actually finds my work useful. Just a heads up, licensing your changes under BSD makes my life easier in regards to backporting your changes, but also means it can be used in commercial projects. Just a heads up so it does not come as a surprise later.
In any way, thanks.

And I agree, quite a few authors don't respond (hell, I only do so occasionally), but it never hurts to try sending a PR or open an issue ;)

**Comment by Bram77** [comment]
I've been sticking with GPLv2 since the whole discussion about GPLv3 and Xbmc (when the v3 license was released). Back then I learned that GPLv2 makes sure it can't be used in commercial applications. That's why I've been sticking with GPLv2. It annoys me if people try to make money from Kodi as a software package. GPLv2 stimulates keeping software free and open. That's all I know :).

**Comment by Bram77** [comment]
But use cases for batch requests....

I'm developing a cross platform remote with Atom Shell/Electron and AngularJS. Electron effectively is Chromium in a wrapper. So it's a web application in which I can use node.js. Because it's a browser performance isn't really that good. Every request to Kodi I can prevent helps. the big advantages are node.js capabilities and instant and reliable cross platform support.

Getting the initial state of Kodi when my application starts is one area where performance can be improved. I need to do multiple requests simultaneously to get the initial state.

There are two situations I really need batch requests, at the moment. 

1. I'm allowing users to create playlists locally. I'm offering the option to save the current playlist (although I've disabled that option for now). The playlists is an array of file paths. Kodi does not provide an option to add multiple file paths to the playlist at once. So when loading a saved playlist the only solution is to iterate trough the array and one by one call Playlist.Add. This isn't working properly. After 5 calls Kodi stops accepting the requests. So only 5 items can be added. Another reason not to do it this way is performance, and it's just plain ugly :).

2. Playlist management in my application offers drag/drop support. The only way to place playlist items in a different position within the current playlist is by swapping (Playlist.Swap -> postion1, position2). So switching an entry from position 10 to position 1 requires 9 requests to Kodi. Which is ugly and inefficient, as you might see. Somehow in this situation more then 5 requests can be executed, but sometimes a timeout occurs and one of the requests doesn't make ik. 

Both these situations can be resolved with batch requests. I'm pretty sure a few more will pop up once I'm a bit further in the development process. The application is far from finished. There still are some asynchronous timing issue, missing features and lots and lots of bugs.

https://github.com/sudo-systems/rekodi

**Comment by Bram77** [comment]
I completely missed your edit. That seems like a logical implementation, with startBatch and endBatch. I'm going to take a swing at it. Thanks a lot!

**Comment by Bram77** [comment]
Too bad Github doesn't send notifications about edits... The forum thread you mention is not the conversation I had with him (my username on the forum is Bram77). [This](http://forum.kodi.tv/showthread.php?tid=237581) is the conversation I was aiming at.

**Comment by PaulAvery** [comment]
Ok, I really (really) have to apologize for thinking that was you then :)
First thing I found, shame on me.

Yeah, I should probably stop editing so much if it messes up notifications. And yeah, those are actually pretty good reasons to implement batch requests.

If you started implementing this, I'll be happy to sit tight. Otherwise I would go ahead and implement it myself. Just don't want to duplicate work if you already started.

**Comment by Bram77** [comment]
No need to apologize :).

I won't have time to start trying to add the functionality until probably coming tuesday. So if you feel like it.... please go ahead! I'm pretty sure your approach will probably be better then mine anyway. I'm guessing you'd probably, at least partially, rewrite my code after merging :-p

**Comment by Bram77** [comment]
I actually don't really understand how the jrpc library can come into play. Does it support sending an array of request objects? It's very likely that it's just me not seeing it....

Anyhow... I've created an ugly but working solution, just to get it working for now. You can see the changes I've made [here](https://github.com/sudo-systems/node-kodi-ws/commit/6837203c1f476991498cb0d5fb7d408d9446134d).

I'm listening for socket messages, which isn't the way to go because it means there are two listeners on the same emitted event. But because I didn't really feel like touching the jrpc library (until I see how to implement batch requests with it) this was the easiest solution.

Kodi always returns an object, unless it's a batch request, then it will return an array of objects. So checking for an Array is my solution to only act on batch results in the socket message listener.

One more thing that isn't very pretty is that I'm introducing another promise. Again because I'm not using the jrpc library.

I'm definitely not content with this solution. How can I implement the jrpc library to accept the array of request objects?

This is how my current code can be used (for example):

```js
          kodiApi.addRequest('VideoLibrary.GetMovies', {
            properties: ['file'],
            sort: {order: 'ascending', method: 'label'}
          }, true);
          kodiApi.addRequest('JSONRPC.Introspect');
          kodiApi.sendBatch().then(function(results) {
            console.dir(results);
          });
```

**Comment by PaulAvery** [comment]
Alright.  Sorry for the almost two week delay. Got kinda swamped. I added batch support just now. Usage is like this:

```js
var batch = connection.batch();
var movies = batch.VideoLibrary.GetMovies({properties: ['title']});
var shows = batch.VideoLibrary.GetTVShows({properties: ['title']});
batch.send();

movies.then(doStuff);
shows.then(doStuff);

/* Or if you want to use them at the same time */
Promise.all([movies, shows]).then(doStuff);
```

Notice that even though, you will receive separate promises per method, a batch request will be send once `batch.send()` is called.

Your basic idea was the right one. As the jrpc library has to keep track of ids though and because I wanted a nice, shortcut-enabled solution I implemented this myself. I hope you don't mind me not building on your code.

**Comment by Bram77** [comment]
Not a problem. I'm in no hurry. I completely understand why you didn't adopt my code. Your approach is much better, as expected.

Your help is very much appreciated! I've started from scratch because the batch request option changes the approach drastically and there were some other fundamental aspects in my app that could do with improvements. Learning every day :).

I can't thank you enough!
